name: ie-bank-infra

on:
  workflow_dispatch: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - '*'
    paths-ignore:
      - 'scripts/**'

env:
  RESOURCE_GROUP_DEV: BCSAI2024-DEVOPS-STUDENTS-B-DEV
  SUBSCRIPTION_ID: e0b9cada-61bc-4b5a-bd7a-52c606726b3b
  USER_ALIAS: troca
  CONTAINER_REGISTRY_NAME: triniacr
  CONTAINER_IMAGE_NAME: flask-app
  CONTAINER_IMAGE_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Install Azure CLI
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az bicep install

      # Step 2: Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 3: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t ${{ env.CONTAINER_REGISTRY_NAME }}.azurecr.io/${{ env.CONTAINER_IMAGE_NAME }}:${{ env.CONTAINER_IMAGE_TAG }} .

      # Step 4: Push Docker Image to ACR
      - name: Push Docker Image to ACR
        run: |
          az acr login --name ${{ env.CONTAINER_REGISTRY_NAME }}
          docker push ${{ env.CONTAINER_REGISTRY_NAME }}.azurecr.io/${{ env.CONTAINER_IMAGE_NAME }}:${{ env.CONTAINER_IMAGE_TAG }}

      # Step 5: Validate and Build Bicep Files
      - name: Validate and Build Bicep Files
        run: |
          az bicep build --file ./main.bicep
          echo "Bicep files successfully built."

      # Step 6: Upload Bicep Build Artifact
      - name: Upload Bicep Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: bicep-build
          path: ./main.bicep

  deploy-dev:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Development

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Download Bicep Build Artifact
      - name: Download Bicep Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: bicep-build

      # Step 3: Login to Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 4: Deploy to Azure
      - name: Deploy to Development Environment
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ env.SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_DEV }}
          template: ./main.bicep
          parameters: ./parameters.json
          deploymentName: ${{ env.USER_ALIAS }}-dev
